- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
        - zsh
        - node
  tasks:
    - includes: tasks/zsh.yml
    - includes: tasks/node.yml
