- name: Clone dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/grantwforsythe/dotfiles.git'
    dest: "{{ lookup('env', 'HOME')}}/dotfiles"
    recursive: true
    update: true
    version: main
  tags:
    - install
    - dotfiles
    - stow
- name: Install Stow
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow
